# Generated by Django 4.2.7 on 2023-11-20 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_remove_task_project_delete_project_delete_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
