# Generated by Django 4.2.7 on 2023-11-29 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='presupuesto',
            field=models.FloatField(default=0.0),
        ),
    ]
